# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 552113b466e9a40c38f1077517c90a822994903d7d3da5f47a6da4925835f7ee967d7ad574e660b7068a218cdf034d2b39ac122642409c57915de9f40a1c427e
  user: 'iiitb_admin'
  password: 'thanks123'
test:
  secret_key_base: c98bc43280afad8074ce620bfec99cdfca6d52a05dcb50853fca80f5f028fa4a0b1664243196f122a0ad35d5e64c315e49b1aa15e4ee18e2ef36fe7dc436688f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8d16e2c81f91911651f43d3a9fb77dd1791bdda758cc304f1ef8b74b15e8f00460fa2d543a9ab73d3c897cc0834b9ea49b0b46ac08fff5af306f9a5186e95ee5
  user: 'iiitb_admin'
  password: 'thanks123'
