# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d22d048f2c473cdcf3d02cd95f07a8d9b34da0966545420451d5fdecf3b7c7aa255da569aa918ccb1dfca3795cd24bf63c05d7ef31aeea5325892dadb4e882
  user: 'iiitb_admin'
  password: 'thanks123'
test:
  secret_key_base: 3d64dbd4a00d64020a04d2bcc539c4509218ad1225b9270246731b8b678b8f473b6575cc8be481ed90d4a9753d8f680dad96587918211b0752b31eab9fefbb18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8d16e2c81f91911651f43d3a9fb77dd1791bdda758cc304f1ef8b74b15e8f00460fa2d543a9ab73d3c897cc0834b9ea49b0b46ac08fff5af306f9a5186e95ee5
  user: 'iiitb_admin'
  password: 'thanks123'
